##########################################
# Python
##########################################
FROM python:3.11.2-slim AS python

# Create app directory
WORKDIR /usr/src/app

# Install packages
COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt


##########################################
# Linter
##########################################
FROM python AS linter

CMD [ "pylint", "--rcfile=.pylintrc", "./todo" ]
